name: zoedepth
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - pip:
      - torch==2.1.0
      - torchvision==0.16.0
      - torchaudio==2.1.0
      - transformers>=4.30,<5.0
      - opencv-python==4.8.1.78
